---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: deploy_view
rules:
- apiGroups:
  - ""
  resources: 
    - pods
  verbs:
  - 'get'
  - 'watch'
  - 'list'
- apiGroups:
  - 'apps'
  resources:
  - deployments
  verbs:
  - 'get'
  - 'watch'
  - 'list'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: deploy_edit
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs: 
    - '*'
- apiGroups:
  - 'apps'
  resources:
  - deployments
  verbs: 
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy_edit
subjects:
- kind: User
  name: deploy_edit
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: deploy_edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy_view
subjects:
- kind: User
  name: deploy_view
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: deploy_view
  apiGroup: rbac.authorization.k8s.io