---
apiVersion: v1
kind: Secret
metadata:
  name: hw43-secret
  annotations:
    kubernetes.io/service-account.name: hw43-sa
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hw43-sa
  namespace: default
secrets:
- name: hw43-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hw43-rb
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: hw43-sa
  namespace: default