---
apiVersion: v1
kind: Service
metadata:
  name: myminio-service1
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress1
spec:
  defaultBackend:
    service:
      name: myminio-service1
      port:
        number: 9001