---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: httpd:2.4
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: cache-volume
            mountPath: /cache
      volumes:
        - name: cache-volume
          emptyDir: {}
