version: '3'
services:
  frontend:
    image: front:latest
    restart: always
    ports:
        - 3000:3000
    networks:
      - lab-network
    depends_on:
      - backend
  backend:
    image: back:latest
    restart: always
    ports:
      - 8000:8000
    networks:
      - lab-network
    depends_on:
      - database
  database:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - lab-network
networks:
  lab-network:
    driver: bridge
volumes:
  postgres-data:
